// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EXPEDIT.Roster.Models.Json
{

    public class Allocation
    {

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("asset")]
        public Asset2 Asset { get; set; }

        [JsonProperty("assetGroup")]
        public AssetGroup2 AssetGroup { get; set; }

        [JsonProperty("ticksOffset")]
        public int TicksOffset { get; set; }

        [JsonProperty("ticks")]
        public int Ticks { get; set; }

        [JsonProperty("blocks")]
        public object[][] Blocks { get; set; }

        [JsonProperty("geolocation")]
        public Geolocation2 Geolocation { get; set; }
    }

}
