// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EXPEDIT.Roster.Models.Json
{

    public class Asset
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("min")]
        public int Min { get; set; }

        [JsonProperty("max")]
        public int Max { get; set; }

        [JsonProperty("antecedents")]
        public Antecedent[] Antecedents { get; set; }

        [JsonProperty("constraints")]
        public Constraint[] Constraints { get; set; }

        [JsonProperty("costs")]
        public Cost[] Costs { get; set; }

        [JsonProperty("priority")]
        public int Priority { get; set; }

        [JsonProperty("capacities")]
        public Capacity[] Capacities { get; set; }

        [JsonProperty("availability")]
        public object[][] Availability { get; set; }

        [JsonProperty("geolocation")]
        public Geolocation Geolocation { get; set; }

        [JsonProperty("assetGroups")]
        public object[] AssetGroups { get; set; }
    }

}
