// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EXPEDIT.Roster.Models.Json
{

    public class Problem
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("version")]
        public int Version { get; set; }

        [JsonProperty("min")]
        public int Min { get; set; }

        [JsonProperty("max")]
        public int Max { get; set; }

        [JsonProperty("iterations")]
        public int Iterations { get; set; }

        [JsonProperty("liveUpdateClient")]
        public bool LiveUpdateClient { get; set; }

        [JsonProperty("liveUpdateServer")]
        public bool LiveUpdateServer { get; set; }

        [JsonProperty("complexity")]
        public int Complexity { get; set; }

        [JsonProperty("costTypes")]
        public CostType[] CostTypes { get; set; }

        [JsonProperty("virtualAssets")]
        public VirtualAsset[] VirtualAssets { get; set; }
    }

}
