// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EXPEDIT.Roster.ViewModels.Json
{

    public class Capacity
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("size")]
        public double Size { get; set; }

        [JsonProperty("assetGroup")]
        public AssetGroup AssetGroup { get; set; }

        [JsonProperty("rate")]
        public double Rate { get; set; }

        [JsonProperty("unitid")]
        public Guid UnitID { get; set; }
    }

}
