// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EXPEDIT.Roster.ViewModels.Json
{

    public class Constraint
    {

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("constraintType")]
        public ConstraintType ConstraintType { get; set; }

        [JsonProperty("fixed")]
        public bool Fixed { get; set; }

        [JsonProperty("weight")]
        public int Weight { get; set; }

        [JsonProperty("blocks")]
        public object[][] Blocks { get; set; }
    }

}
