// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EXPEDIT.Roster.ViewModels.Json
{

    public class Roster
    {

        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("user")]
        public User User { get; set; }

        [JsonProperty("location")]
        public Geolocation Location { get; set; }

        [JsonProperty("culture")]
        public string Culture { get; set; }

        [JsonProperty("timeResolution")]
        public long TimeResolution { get; set; }

        [JsonProperty("subscription")]
        public Subscription Subscription { get; set; }

        [JsonProperty("problem")]
        public Problem Problem { get; set; }

        [JsonProperty("assets")]
        public Asset[] Assets { get; set; }

        [JsonProperty("solutions")]
        public Solution[] Solutions { get; set; }

        [JsonProperty("costType")]
        public CostType CostType { get; set; }
    }

}
