// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EXPEDIT.Roster.ViewModels.Json
{

    public class Solution
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("min")]
        public int Min { get; set; }

        [JsonProperty("max")]
        public int Max { get; set; }

        [JsonProperty("costs")]
        public Cost[] Costs { get; set; }

        [JsonProperty("costType")]
        public CostType CostType { get; set; }

        [JsonProperty("solutionType")]
        public string SolutionType { get; set; }

        [JsonProperty("iterations")]
        public int Iterations { get; set; }

        [JsonProperty("confidence")]
        public double Confidence { get; set; }

        [JsonProperty("duration")]
        public int Duration { get; set; }

        [JsonProperty("eta")]
        public string Eta { get; set; }

        [JsonProperty("priority")]
        public int Priority { get; set; }

        [JsonProperty("allocations")]
        public Allocation[] Allocations { get; set; }

        [JsonProperty("completed")]
        public bool Completed { get; set; }
    }

}
